import type { ClaimCase } from "./types";

export const cases: ClaimCase[] = [
  {
    id: "SZI-2048",
    provider: "Northstar Diagnostics",
    specialty: "Independent laboratory",
    category: "Coordinated laboratory activity",
    family: "Laboratory",
    status: "Candidate",
    severity: "Critical",
    priority: 94,
    risk: 88,
    exposure: 184260,
    members: 47,
    age: 3,
    evidenceQuality: 91,
    forecasts: { 30: 42, 60: 64, 90: 78 },
    summary: "Repeated laboratory panels, concentrated referrals, and a shared ownership assertion form a reviewable pattern across 47 synthetic members.",
    evidence: [
      { id: "EV-101", label: "Repeated panel groups", detail: "126 paid lines repeat within 7 days for 31 members.", strength: "Strong", source: "claim_lines.csv · 126 rows" },
      { id: "EV-102", label: "Referral concentration", detail: "81% of orders originated from two connected practices; peer median is 23%.", strength: "Strong", source: "referrals.csv · 92 rows" },
      { id: "EV-103", label: "Ownership assertion", detail: "Laboratory and top ordering practice share a simulated organization record.", strength: "Context", source: "relationships.csv · row 118" },
    ],
    explanations: [
      { title: "Unsupported repeat billing", kind: "Suspicious", support: 78, summary: "Repeated paid panels lack visible distinct-specimen records." },
      { title: "Legitimate repeat monitoring", kind: "Legitimate", support: 43, summary: "Separate specimens or acute monitoring could explain the cadence." },
      { title: "Incomplete encounter feed", kind: "Uncertain", support: 31, summary: "Coverage is high, but specimen details are held for human review." },
    ],
    check: {
      title: "Inspect specimen and accession records",
      reason: "This check can distinguish legitimate separate tests from repeated billing and may clear 31 members from the finding.",
      minutes: 12,
      result: "The fixed synthetic vault contains 18 distinct specimens for 31 repeated service groups; 13 groups have no matching distinct specimen record despite complete source coverage.",
      impact: "Evidence narrows the concern from 31 to 13 service groups and reduces gross implicated exposure by $42,180.",
    },
    network: [
      { name: "Northstar Diagnostics", role: "Billing provider", tone: "primary" },
      { name: "SYN-ORG-003", role: "Ownership assertion", tone: "signal" },
      { name: "Harbor Family Care", role: "62% of referrals", tone: "signal" },
      { name: "Pioneer Medical", role: "19% of referrals", tone: "neutral" },
    ],
  },
  {
    id: "SZI-1987",
    provider: "Evergreen Medical Supply",
    specialty: "Durable medical equipment",
    category: "Repeated DME acquisition",
    family: "DME",
    status: "In review",
    severity: "High",
    priority: 86,
    risk: 79,
    exposure: 96740,
    members: 29,
    age: 7,
    evidenceQuality: 84,
    forecasts: { 30: 31, 60: 48, 90: 61 },
    summary: "Overlapping rental and purchase activity appears across three synthetic item groups, with incomplete delivery evidence.",
    evidence: [
      { id: "EV-201", label: "Rental overlap", detail: "22 members show overlapping rental months for an equivalent item group.", strength: "Strong", source: "claim_lines.csv · 54 rows" },
      { id: "EV-202", label: "Delivery mismatch", detail: "Nine billed acquisitions do not match visible delivery records.", strength: "Moderate", source: "deliveries.csv · coverage 94%" },
      { id: "EV-203", label: "Growth deviation", detail: "Paid acquisition volume is 3.4× the provider's prior 90-day baseline.", strength: "Moderate", source: "feature snapshot · v1.2" },
    ],
    explanations: [
      { title: "Overlapping acquisitions", kind: "Suspicious", support: 72, summary: "Rental windows overlap without a visible replacement reason." },
      { title: "Valid replacement equipment", kind: "Legitimate", support: 49, summary: "Damage or medical change could justify replacement." },
      { title: "Delivery feed gap", kind: "Uncertain", support: 35, summary: "Six percent of delivery records are unavailable." },
    ],
    check: {
      title: "Reconcile replacement authorizations",
      reason: "Authorization records could explain the highest-value overlapping items before broader review.",
      minutes: 18,
      result: "Fourteen overlaps have valid synthetic replacement authorizations. Eight remain unsupported after authorization reconciliation.",
      impact: "The review scope falls from 22 to 8 members and estimated excess exposure falls to $31,420.",
    },
    network: [
      { name: "Evergreen Medical Supply", role: "Billing supplier", tone: "primary" },
      { name: "SYN-FAC-014", role: "Primary delivery facility", tone: "neutral" },
      { name: "Orion Orthopedics", role: "38% of orders", tone: "signal" },
      { name: "29 members", role: "Affected population", tone: "neutral" },
    ],
  },
  {
    id: "SZI-1924",
    provider: "Riverside Behavioral Group",
    specialty: "Behavioral health",
    category: "Impossible service timing",
    family: "Behavioral health",
    status: "Needs information",
    severity: "High",
    priority: 80,
    risk: 74,
    exposure: 68420,
    members: 18,
    age: 12,
    evidenceQuality: 67,
    forecasts: { 30: 24, 60: 39, 90: 53 },
    summary: "Individual session durations appear to exceed available clinician time, but group-session coding remains unresolved.",
    evidence: [
      { id: "EV-301", label: "Concurrent sessions", detail: "Nine clinician-days exceed 15 billed individual-service hours.", strength: "Strong", source: "claim_lines.csv · 63 rows" },
      { id: "EV-302", label: "Setting ambiguity", detail: "Session format is missing from 27% of affected lines.", strength: "Context", source: "claim_extensions.csv" },
      { id: "EV-303", label: "Peer deviation", detail: "Provider is at the 98.2 percentile for individual hours per clinician-day.", strength: "Moderate", source: "anomaly model · IF-v3" },
    ],
    explanations: [
      { title: "Overlapping individual services", kind: "Suspicious", support: 68, summary: "Visible line durations cannot be delivered sequentially." },
      { title: "Group-session miscoding", kind: "Legitimate", support: 52, summary: "Some lines may represent simultaneous group treatment." },
      { title: "Clinician identity mismatch", kind: "Uncertain", support: 38, summary: "A billing-to-rendering mapping issue remains possible." },
    ],
    check: {
      title: "Verify session format and renderer roster",
      reason: "A targeted roster check could resolve both leading alternative explanations in one review step.",
      minutes: 15,
      result: "The synthetic roster confirms two clinicians were mapped correctly. Eleven lines were group sessions; seven overlapping individual sessions remain unresolved.",
      impact: "The finding remains supported for seven lines and the initial dollar scope declines by 63%.",
    },
    network: [
      { name: "Riverside Behavioral Group", role: "Billing organization", tone: "primary" },
      { name: "SYN-CLIN-018", role: "Rendering clinician", tone: "signal" },
      { name: "SYN-FAC-022", role: "Service facility", tone: "neutral" },
      { name: "18 members", role: "Affected population", tone: "neutral" },
    ],
  },
  {
    id: "SZI-1881",
    provider: "Summit Primary Care",
    specialty: "Professional services",
    category: "Coding intensity shift",
    family: "Professional",
    status: "Candidate",
    severity: "Medium",
    priority: 72,
    risk: 65,
    exposure: 41780,
    members: 64,
    age: 2,
    evidenceQuality: 73,
    forecasts: { 30: 18, 60: 28, 90: 37 },
    summary: "Higher-intensity service mix increased sharply compared with matched synthetic peers and prior behavior.",
    evidence: [
      { id: "EV-401", label: "Intensity shift", detail: "High-intensity share moved from 21% to 59% in 60 days.", strength: "Moderate", source: "provider feature window" },
      { id: "EV-402", label: "Peer comparison", detail: "Matched peer median is 26% across 42 synthetic practices.", strength: "Moderate", source: "peer cohort PG-14" },
      { id: "EV-403", label: "Capacity increase", detail: "Provider capacity grew 31% during the same period.", strength: "Context", source: "providers.csv · version 4" },
    ],
    explanations: [
      { title: "Coding intensity mismatch", kind: "Suspicious", support: 61, summary: "The change exceeds peers after available case-mix controls." },
      { title: "Practice expansion", kind: "Legitimate", support: 58, summary: "Capacity and referral mix both changed during the period." },
      { title: "Insufficient clinical context", kind: "Uncertain", support: 45, summary: "Claims cannot establish documentation support." },
    ],
    check: {
      title: "Review a stratified service sample",
      reason: "A small sample across old and new referral sources can test whether the shift follows documented complexity.",
      minutes: 25,
      result: "Synthetic documentation supports 16 of 20 sampled services. Four remain insufficiently documented and require human interpretation.",
      impact: "The case remains inconclusive; evidence does not support a provider-wide conclusion.",
    },
    network: [
      { name: "Summit Primary Care", role: "Rendering practice", tone: "primary" },
      { name: "SYN-FAC-031", role: "New affiliated clinic", tone: "neutral" },
      { name: "64 members", role: "Observed population", tone: "neutral" },
      { name: "Peer group PG-14", role: "42 practices", tone: "neutral" },
    ],
  },
];
